<a href="https://colab.research.google.com/github/siwakornnn/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dictionary

สามารถ index ด้วยอะไรก็ได้ แต่ลำดับจะหายไป

In [ ]:
ex_dict = {'a':10, '1':1, 'stat':5} #curly brackets ในการบอกว่าเป็น dict

In [ ]:
ex_dict['stat']

5

In [ ]:
ex2_dict = {1:'one', 2:'two', 3:'three'}

In [ ]:
ex2_dict[1]

'one'

### การเพิ่มสมาชิกใน dict

In [ ]:
ex2_dict[0] = 'zero'

In [ ]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

คำสั่ง

In [ ]:
ex2_dict.keys()

dict_keys([1, 2, 3, 0])

In [ ]:
for index in ex2_dict.keys():
     print(index)

1
2
3
0


ex2_dict.values()

dict เอาไปใช้ร่วมกับ Datframe ของ pa

numpy คือ package ที่ทำงานกี่ยวกับ array ของตัวเลข (ที่มีคนเขียนขึ้นมาและนิยมใช้)

numpy -> number python

In [ ]:
import numpy #วิธีเรียกใช้งาน package

In [ ]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


การชี้ค่าใน numpy array

In [ ]:
ex_2d_array[1,2]

0.3

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] #การชี้ list
print(len(list_x)) #หาจำนวนสมาชิก
print(list_x[1])
print(list_x[1][2])

2
[9.1, 0.1, 0.3]
0.3


### Operations

In [ ]:
ex2_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex2_2d_array.shape #ตรวจสอบขนาดของ matrix

(2, 3)

In [ ]:
ex_2d_array + ex2_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]
list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 0], [0, 0, 1]]

In [ ]:
ex_2d_array - ex2_2d_array

array([[ 4.2,  3. ,  4.5],
       [ 9.1,  0.1, -0.7]])

In [ ]:
dot_mat = numpy.dot(ex_2d_array,ex2_2d_array.T)
print(dot_mat)

[[5.2 4.5]
 [9.1 0.3]]


In [ ]:
numpy.linalg.det(dot_mat)

-39.389999999999986

search google -> stackoverflow หรือ web ของ package สำหรับ operations อื่นๆ 

##matrix slicing

In [ ]:
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array[1,1:]

array([0.1, 0.3])

In [ ]:
ex_2d_array[:,:2]

array([[5.2, 3. ],
       [9.1, 0.1]])

HW5 เขียน function คูณ matrix

> บล็อกที่มีการเยื้อง


แล้ว test กับ matrix ขนาด
(2,3)*(3,2)
(4,4)*(4,1)
(2,2)*(2,2)

In [ ]:
import numpy as np

In [ ]:
#(2,3) A
A = np.array([[5.4,3.5,0.0],[6.4,1.8,4.3]]) 
#(3,2) B
B = np.array([[4.9,5.6],[9.3,8.2],[6.3,96]])
#(4,4) C
C = np.array([[8.5,4.3,9.6,7.8],[6.5,5.3,8.8,4.4],[8.6,8.9,7.5,9.9],[5.6,8.4,1.5,1.8]])
#(4,1) D
D = np.array([[5.0],[5.6],[9.4],[5.5]])
#(2,2) E
E = np.array([[1.1,1.1],[1.1,1.1]])
#(2,2) F
F = np.array([[4.6,6.4],[4.4,6.6]])

In [ ]:
print(f'A = {A}\n\n\
B = {B}\n\n\
C = {C}\n\n\
D = {D}\n\n\
E = {E}\n\n\
F = {F}\n')

A = [[5.4 3.5 0. ]
 [6.4 1.8 4.3]]

B = [[ 4.9  5.6]
 [ 9.3  8.2]
 [ 6.3 96. ]]

C = [[8.5 4.3 9.6 7.8]
 [6.5 5.3 8.8 4.4]
 [8.6 8.9 7.5 9.9]
 [5.6 8.4 1.5 1.8]]

D = [[5. ]
 [5.6]
 [9.4]
 [5.5]]

E = [[1.1 1.1]
 [1.1 1.1]]

F = [[4.6 6.4]
 [4.4 6.6]]



HW5 เขียน function คูณ matrix แล้ว test กับ matrix ขนาด
*   (2,3)*(3,2)
*   (4,4)*(4,1)
*   (2,2)*(2,2)

In [1]:
import numpy as np

In [2]:
#Matrix 2*3
mat_A = np.array([[1,4,2],[2,8,7]])
mat_A

array([[1, 4, 2],
       [2, 8, 7]])

In [3]:
#Matrix 3*2
mat_B = np.array([[4,2],[6,8],[2,1]])
mat_B

array([[4, 2],
       [6, 8],
       [2, 1]])

In [4]:
#Matrix 4*4
mat_C = np.array([[1,5,4,3],[5,2,1,4],[9,6,2,4],[1,3,2,4]])
mat_C

array([[1, 5, 4, 3],
       [5, 2, 1, 4],
       [9, 6, 2, 4],
       [1, 3, 2, 4]])

In [5]:
#Matrix 4*1
mat_D = np.array([[1],[4],[5],[7]])
mat_D

array([[1],
       [4],
       [5],
       [7]])

In [6]:
#Matrix 2*2 
mat_E = np.array([[5,1],[4,2]])
mat_E

array([[5, 1],
       [4, 2]])

In [7]:
mat_F = np.array([[1,8],[7,3]])
mat_F

array([[1, 8],
       [7, 3]])

In [9]:
def mul_mat(a, b) :
  c = [[0 for row in range(len(b[0]))] for col in range(len(a))]
  for i in range(len(a)) :
    for j in range(len(b[0])) :
      for k in range(len(b)) :
        c[i][j] += a[i][k]*b[k][j]
  r = np.matrix(c)
  return r

In [12]:
mul_mat(mat_A,mat_B) #(2,3)*(3,2)

matrix([[32, 36],
        [70, 75]])

In [14]:
mul_mat(mat_C,mat_D) #(4,4)*(4,1)

matrix([[62],
        [46],
        [71],
        [51]])

In [15]:
mul_mat(mat_E,mat_F) #(2,2)*(2,2)

matrix([[12, 43],
        [18, 38]])

ตรวจสอบความถูกต้อง

In [16]:
np.dot(mat_A,mat_B)

array([[32, 36],
       [70, 75]])